name: "Mark old issues as 'stale'"

on:
  schedule:
  - cron: "* * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 180
        days-before-close: -1
        stale-issue-message: "This issue has not had any activity for 6 months and has been marked as 'stale'."
        stale-issue-label: stale
